# The URL the site will be built for
base_url = "https://www.zaynetro.com"

title = "Roman Zaynetdinov (zaynetro)"
description = "Welcome to my personal blog! I write about different technologies and things I am working on."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# RSS feed: https://www.getzola.org/documentation/templates/feeds/
generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# highlight_theme = "solarized-light"

# Instead of using a fixed theme we can ask zola to generate a stylesheet file for each theme.
# Then we import the CSS file based on user dark-mode preference.
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]

[extra]
github = "zaynetro"
cv = "https://www.linkedin.com/in/roman-zay/"
footer_text = "Roman Zaynetdinov (zaynetro)"
site_source = "https://github.com/zaynetro/zaynetro.com"
email = "roman@zaynetro.com"
