####################
# Hugo Settings
####################

baseurl = "https://www.zaynetro.com/"
languageCode = "en-US"
theme = "zaynetro"

title = "zaynetro"

paginate = 20

[params]

email = ""
github = "zaynetro"
cv = "https://stackoverflow.com/story/zaynetro"
footer_text = "Roman Zaynetdinov (zaynetro)"
site_source = "https://github.com/zaynetro/zaynetro.com"
