# Master
[build]
command = "zola build"
publish = "public"

[context.production.environment]
ZOLA_VERSION = "0.16.1"


# Merge requests
[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
ZOLA_VERSION = "0.16.1"


# Branches
[context.branch-deploy]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
ZOLA_VERSION = "0.16.1"


[[redirects]]
from = "/js/stats.js"
to = "https://plausible.io/js/script.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 200
